// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYBq7JtfRH0YXc63CeZE-JjfZt1F5z8M',
    appId: '1:878726794935:web:e1f8ce6d0445f7819c8732',
    messagingSenderId: '878726794935',
    projectId: 'todo-6aa24',
    authDomain: 'todo-6aa24.firebaseapp.com',
    storageBucket: 'todo-6aa24.firebasestorage.app',
    measurementId: 'G-XXRS1Y0PS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi8jlz3TghOwnPi8jQ8ueD_58CED-uez0',
    appId: '1:878726794935:android:d000afee0e7caef09c8732',
    messagingSenderId: '878726794935',
    projectId: 'todo-6aa24',
    storageBucket: 'todo-6aa24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYujooDamb1SfurzvrIILmvhbxpU_vB5E',
    appId: '1:878726794935:ios:5d25ada9d313d4009c8732',
    messagingSenderId: '878726794935',
    projectId: 'todo-6aa24',
    storageBucket: 'todo-6aa24.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYujooDamb1SfurzvrIILmvhbxpU_vB5E',
    appId: '1:878726794935:ios:5d25ada9d313d4009c8732',
    messagingSenderId: '878726794935',
    projectId: 'todo-6aa24',
    storageBucket: 'todo-6aa24.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhYBq7JtfRH0YXc63CeZE-JjfZt1F5z8M',
    appId: '1:878726794935:web:96a62ab78801268e9c8732',
    messagingSenderId: '878726794935',
    projectId: 'todo-6aa24',
    authDomain: 'todo-6aa24.firebaseapp.com',
    storageBucket: 'todo-6aa24.firebasestorage.app',
    measurementId: 'G-201821EHXT',
  );
}
